### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by andrewlorien**
While investigating the project, one of my collaborators said "I wish the README file would give you a clue about what sort of tool it is, and how hard it will be to set up".  I think my change satisfies that.
Also, a couple of minor formatting changes to the docs.

### CODE REVIEW

**Comment by odscjames** [comment]
Hello Andrew, good to hear from you! Sorry it's hard to set up - can you give us some more details on that? It would be good to know what problems there were to see if we can solve them.

Specifically:

> It requires ..... a postgresql database.

It is actually meant to work without one - it can't store things and check them, but it can still be used to download files to disk. Maybe that's something we need to make clearer, maybe a specific page in the docs?

**Comment by jpmckinney** [comment]
A database is presently required (see #167), though hopefully not for long.

**Comment by andrewlorien** [comment]
It wasn't hard to set up (for me).  But looking at the README with a couple of people with varying technical skills, it wasn't clear who should take on the job.  Was kingfisher an application anybody could run?  something we could suggest to a person with a few technical skills?  Or do you need commandline skills to even get started?
The update to the README intended to answer those questions in as few words as possible.  Pretty much "if you understand this sentence you can use me"

**Comment by odscjames** [comment]
Thanks - I'm happy with those changes. Just out of curiosity, is there a technical reason to put single sentences all on one line or is that a style thing?

**Comment by andrewlorien** [comment]
The line breaks make it hard to read in an editor which has line breaks turned on.  I guess it's just a style preference, unless we want to think about the semantic implications of various types of whitespace.  I don't want to think about that!

**Pull request merged**
