### PR TITLE
Clean Master - remove code, and set docs back to a basic state ready for future work.

### PR DESCRIPTION
**Pull request by odscjames**
This is not to say all the docs I've deleted are bad - some of them may come back (I in fact will make some tickets now). But they all need checking at the very least, so this sets it to a blank state that several of us will be trying to build on this week.

https://github.com/open-contracting/kingfisher/issues/284

### CODE REVIEW

**Comment by robredpath** [comment]
Thanks for this, @odscjames . So I should branch off clean-master and then this PR will be used to assess the whole changeset to the docs before merging in?

**Comment by odscjames** [comment]
If your happy with this shall we approve it and just merge it to master? Then we are improving master in small steps rather than one big thing, which I'd prefer. You can then P.R. directly against master.

**Comment by robredpath** [comment]
...but then, aren't we replacing a good (but old) master with basically nothing; not even a note to say where everything went? I'd much rather get the docs in place and then make the switch once we're ready

**Comment by jpmckinney** [comment]
I skimmed the patch, and it looks like it becomes a readme that links to readthedocs, which essentially has an index page and two pages that link to the new repos and their docs.

This seems reasonable, and better than leaving old code up that people can very easily confuse as being the code we still want to put forward – rather than directing them to the new repos.

**Comment by robredpath** [comment]
Can we at least add something to say where the old docs are? If you've got the old code and you're looking for docs, you might reasonably look at the repo and be surprised to find nothing relevant.

**Comment by jpmckinney** [comment]
Sure – let's tag and keep a build of the old docs on readthedocs.

**Comment by odscjames** [comment]
The old docs will be available on the "archive" branch - I've already enabled that on RTD. I'll add a short page to this P.R. with that now, then hopefully we can get this in.

**Pull request merged**
