### PR TITLE
Hard break when loading files with invalid encoding

### PR DESCRIPTION
**Pull request by tian2992**
When loading files from publishers that have invalid encoding set, this skips the invalid files and warns of the exception.

### CODE REVIEW

**Comment by odscjames** [comment]
Hello!

Have you come across a case where this is a problem for you? How can we replicate that?

I'm just trying to think through the effects of putting the "continue" in. (When looking at the database contents, it would appear as if the file hadn't been stored, but with no indication as to why.)

**Comment by odscjames** [comment]
Is there any way we can recover from the error?

Or do we just have to throw the file away and mark it as bad?

(Sorry, I'm going to a workshop today so I can't try any code myself today!)

**Comment by tian2992** [comment]
I think it depends on the exception raised, maybe retry if its bad
encoding? discard if it is just invalid json?

BTW, uruguay fixed the issue on their end already, still GACM remains

**Comment by odscjames** [comment]
> GACM-Mexico

Sorry, which Mexico one? I just ran samples of them all and can't reproduce.

**Comment by odscjames** [comment]
Closing, as this has moved to Process code

**Pull request closed without merging**
