### PR TITLE
Add database migrations to postgresql data base

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/open-contracting/ocdsdata/issues/48

### CODE REVIEW

**Comment by odscjames** [comment]
Ok, some feedback would be good! 

(Should probably write the downgrade path for the one DB migration we have! Do we tend to do those? I know some people don't.)

- There is now DB migrations ...
- The tests use them.
- There is a new central config file to get DB stuff, ocdsdata/maindatabase/config.py

I took the database commands out of the CLI - it's in readme. Could put the back in CLI?

It's maybe a bit dumb to have both the package odcsdata/maindatabase and the file odscdata/database.py - could deal with that later, or move database.py into odcsdata/maindatabase/lib.py or something?

**Comment by odscjames** [comment]
Oh wait, I need to add this to setup.py. Working out how to do that ...

**Comment by odscjames** [comment]
Did setup.py.

Put CLI commands back in at request of @kindly

**Review by kindly — DISMISSED** [review]
I am happy with this pull request.

What I would like to see is though a bit of documentation in the readme on how one would write a migration in future (or at least a pointer to the alembic docs on how todo that) as this would save people a lot of time.

It would be good if that was added to this pull request but could also be done in a separate issue.

**Comment by odscjames** [comment]
Good point, done, want to review again? :-) @kindly

**Review by kindly — APPROVED** [review]

**Pull request merged**
