### PR TITLE
Users can rerun checks against a different schema version

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/open-contracting/ocdsdata/issues/119

### CODE REVIEW

**Comment by odscjames** [comment]
Tagging @kindly as I know he mentioned this before and may want to discuss the general approach I've taken for this.

**Review by kindly — DISMISSED** [review]
Happy with the code.

I am worried that we are overcomplicating things allowing this override as I am not sure that we are going about this in the best way.
I think we need some more requirements gathering about what what transformations/checks that we need.

Nonetheless, happy to merge as it is not doing any harm.

**Comment by jpmckinney** [comment]
Agreed with @kindly's comment. I've raised this before, so created #172.

**Comment by odscjames** [comment]
Having chatted to @kindly, I'm going to leave this P.R. for now. First I'm going to double check user stories and also digest and comment on #172.

**Comment by odscjames** [comment]
Having had a chat with @timgdavies about the user needs, and reading over #172, I'm happy to press ahead with this as is.

There are 2 distinct user needs here:
  *  Run the check against a data as is, but with a different version number. See #119 
  *  Transform the data from 1.0 to 1.1 and then recheck (and do other analysis)

The second of these user cases should be dealt with by something like transforms - see #172.

The first user case, however, can I think be dealt with more efficiently by this pull request. Done as a transform means using more disk space, where as this is pretty efficient.

I'll fix the merge conflict and send this up.

**Comment by jpmckinney** [comment]
When we get around to discussing #172, I think we'll be able to find creative ways to avoid using more disk space. But, I have no issue with merging this, with the option to refactor at a later date.

**Review by kindly — APPROVED** [review]

**Pull request merged**
